#!/bin/bash
set -e

filesToFormat="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.nb/ { print $2}')"

if [ "$filesToFormat" != "" ]; then
    wolframscript Scripts/FormatNotebooks.wls --notebooks="$filesToFormat"

    for sourceFilePath in $filesToFormat
    do
    git add $sourceFilePath
    done;

fi
